# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jrb/efsw

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jrb/efsw

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jrb/efsw/CMakeFiles /home/jrb/efsw/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jrb/efsw/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named efsw

# Build rule for target.
efsw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 efsw
.PHONY : efsw

# fast build rule for target.
efsw/fast:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/build
.PHONY : efsw/fast

src/efsw/Debug.o: src/efsw/Debug.cpp.o

.PHONY : src/efsw/Debug.o

# target to build an object file
src/efsw/Debug.cpp.o:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/Debug.cpp.o
.PHONY : src/efsw/Debug.cpp.o

src/efsw/Debug.i: src/efsw/Debug.cpp.i

.PHONY : src/efsw/Debug.i

# target to preprocess a source file
src/efsw/Debug.cpp.i:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/Debug.cpp.i
.PHONY : src/efsw/Debug.cpp.i

src/efsw/Debug.s: src/efsw/Debug.cpp.s

.PHONY : src/efsw/Debug.s

# target to generate assembly for a file
src/efsw/Debug.cpp.s:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/Debug.cpp.s
.PHONY : src/efsw/Debug.cpp.s

src/efsw/DirWatcherGeneric.o: src/efsw/DirWatcherGeneric.cpp.o

.PHONY : src/efsw/DirWatcherGeneric.o

# target to build an object file
src/efsw/DirWatcherGeneric.cpp.o:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/DirWatcherGeneric.cpp.o
.PHONY : src/efsw/DirWatcherGeneric.cpp.o

src/efsw/DirWatcherGeneric.i: src/efsw/DirWatcherGeneric.cpp.i

.PHONY : src/efsw/DirWatcherGeneric.i

# target to preprocess a source file
src/efsw/DirWatcherGeneric.cpp.i:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/DirWatcherGeneric.cpp.i
.PHONY : src/efsw/DirWatcherGeneric.cpp.i

src/efsw/DirWatcherGeneric.s: src/efsw/DirWatcherGeneric.cpp.s

.PHONY : src/efsw/DirWatcherGeneric.s

# target to generate assembly for a file
src/efsw/DirWatcherGeneric.cpp.s:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/DirWatcherGeneric.cpp.s
.PHONY : src/efsw/DirWatcherGeneric.cpp.s

src/efsw/DirectorySnapshot.o: src/efsw/DirectorySnapshot.cpp.o

.PHONY : src/efsw/DirectorySnapshot.o

# target to build an object file
src/efsw/DirectorySnapshot.cpp.o:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/DirectorySnapshot.cpp.o
.PHONY : src/efsw/DirectorySnapshot.cpp.o

src/efsw/DirectorySnapshot.i: src/efsw/DirectorySnapshot.cpp.i

.PHONY : src/efsw/DirectorySnapshot.i

# target to preprocess a source file
src/efsw/DirectorySnapshot.cpp.i:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/DirectorySnapshot.cpp.i
.PHONY : src/efsw/DirectorySnapshot.cpp.i

src/efsw/DirectorySnapshot.s: src/efsw/DirectorySnapshot.cpp.s

.PHONY : src/efsw/DirectorySnapshot.s

# target to generate assembly for a file
src/efsw/DirectorySnapshot.cpp.s:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/DirectorySnapshot.cpp.s
.PHONY : src/efsw/DirectorySnapshot.cpp.s

src/efsw/DirectorySnapshotDiff.o: src/efsw/DirectorySnapshotDiff.cpp.o

.PHONY : src/efsw/DirectorySnapshotDiff.o

# target to build an object file
src/efsw/DirectorySnapshotDiff.cpp.o:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/DirectorySnapshotDiff.cpp.o
.PHONY : src/efsw/DirectorySnapshotDiff.cpp.o

src/efsw/DirectorySnapshotDiff.i: src/efsw/DirectorySnapshotDiff.cpp.i

.PHONY : src/efsw/DirectorySnapshotDiff.i

# target to preprocess a source file
src/efsw/DirectorySnapshotDiff.cpp.i:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/DirectorySnapshotDiff.cpp.i
.PHONY : src/efsw/DirectorySnapshotDiff.cpp.i

src/efsw/DirectorySnapshotDiff.s: src/efsw/DirectorySnapshotDiff.cpp.s

.PHONY : src/efsw/DirectorySnapshotDiff.s

# target to generate assembly for a file
src/efsw/DirectorySnapshotDiff.cpp.s:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/DirectorySnapshotDiff.cpp.s
.PHONY : src/efsw/DirectorySnapshotDiff.cpp.s

src/efsw/FileInfo.o: src/efsw/FileInfo.cpp.o

.PHONY : src/efsw/FileInfo.o

# target to build an object file
src/efsw/FileInfo.cpp.o:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/FileInfo.cpp.o
.PHONY : src/efsw/FileInfo.cpp.o

src/efsw/FileInfo.i: src/efsw/FileInfo.cpp.i

.PHONY : src/efsw/FileInfo.i

# target to preprocess a source file
src/efsw/FileInfo.cpp.i:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/FileInfo.cpp.i
.PHONY : src/efsw/FileInfo.cpp.i

src/efsw/FileInfo.s: src/efsw/FileInfo.cpp.s

.PHONY : src/efsw/FileInfo.s

# target to generate assembly for a file
src/efsw/FileInfo.cpp.s:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/FileInfo.cpp.s
.PHONY : src/efsw/FileInfo.cpp.s

src/efsw/FileSystem.o: src/efsw/FileSystem.cpp.o

.PHONY : src/efsw/FileSystem.o

# target to build an object file
src/efsw/FileSystem.cpp.o:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/FileSystem.cpp.o
.PHONY : src/efsw/FileSystem.cpp.o

src/efsw/FileSystem.i: src/efsw/FileSystem.cpp.i

.PHONY : src/efsw/FileSystem.i

# target to preprocess a source file
src/efsw/FileSystem.cpp.i:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/FileSystem.cpp.i
.PHONY : src/efsw/FileSystem.cpp.i

src/efsw/FileSystem.s: src/efsw/FileSystem.cpp.s

.PHONY : src/efsw/FileSystem.s

# target to generate assembly for a file
src/efsw/FileSystem.cpp.s:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/FileSystem.cpp.s
.PHONY : src/efsw/FileSystem.cpp.s

src/efsw/FileWatcher.o: src/efsw/FileWatcher.cpp.o

.PHONY : src/efsw/FileWatcher.o

# target to build an object file
src/efsw/FileWatcher.cpp.o:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/FileWatcher.cpp.o
.PHONY : src/efsw/FileWatcher.cpp.o

src/efsw/FileWatcher.i: src/efsw/FileWatcher.cpp.i

.PHONY : src/efsw/FileWatcher.i

# target to preprocess a source file
src/efsw/FileWatcher.cpp.i:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/FileWatcher.cpp.i
.PHONY : src/efsw/FileWatcher.cpp.i

src/efsw/FileWatcher.s: src/efsw/FileWatcher.cpp.s

.PHONY : src/efsw/FileWatcher.s

# target to generate assembly for a file
src/efsw/FileWatcher.cpp.s:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/FileWatcher.cpp.s
.PHONY : src/efsw/FileWatcher.cpp.s

src/efsw/FileWatcherCWrapper.o: src/efsw/FileWatcherCWrapper.cpp.o

.PHONY : src/efsw/FileWatcherCWrapper.o

# target to build an object file
src/efsw/FileWatcherCWrapper.cpp.o:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/FileWatcherCWrapper.cpp.o
.PHONY : src/efsw/FileWatcherCWrapper.cpp.o

src/efsw/FileWatcherCWrapper.i: src/efsw/FileWatcherCWrapper.cpp.i

.PHONY : src/efsw/FileWatcherCWrapper.i

# target to preprocess a source file
src/efsw/FileWatcherCWrapper.cpp.i:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/FileWatcherCWrapper.cpp.i
.PHONY : src/efsw/FileWatcherCWrapper.cpp.i

src/efsw/FileWatcherCWrapper.s: src/efsw/FileWatcherCWrapper.cpp.s

.PHONY : src/efsw/FileWatcherCWrapper.s

# target to generate assembly for a file
src/efsw/FileWatcherCWrapper.cpp.s:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/FileWatcherCWrapper.cpp.s
.PHONY : src/efsw/FileWatcherCWrapper.cpp.s

src/efsw/FileWatcherGeneric.o: src/efsw/FileWatcherGeneric.cpp.o

.PHONY : src/efsw/FileWatcherGeneric.o

# target to build an object file
src/efsw/FileWatcherGeneric.cpp.o:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/FileWatcherGeneric.cpp.o
.PHONY : src/efsw/FileWatcherGeneric.cpp.o

src/efsw/FileWatcherGeneric.i: src/efsw/FileWatcherGeneric.cpp.i

.PHONY : src/efsw/FileWatcherGeneric.i

# target to preprocess a source file
src/efsw/FileWatcherGeneric.cpp.i:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/FileWatcherGeneric.cpp.i
.PHONY : src/efsw/FileWatcherGeneric.cpp.i

src/efsw/FileWatcherGeneric.s: src/efsw/FileWatcherGeneric.cpp.s

.PHONY : src/efsw/FileWatcherGeneric.s

# target to generate assembly for a file
src/efsw/FileWatcherGeneric.cpp.s:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/FileWatcherGeneric.cpp.s
.PHONY : src/efsw/FileWatcherGeneric.cpp.s

src/efsw/FileWatcherImpl.o: src/efsw/FileWatcherImpl.cpp.o

.PHONY : src/efsw/FileWatcherImpl.o

# target to build an object file
src/efsw/FileWatcherImpl.cpp.o:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/FileWatcherImpl.cpp.o
.PHONY : src/efsw/FileWatcherImpl.cpp.o

src/efsw/FileWatcherImpl.i: src/efsw/FileWatcherImpl.cpp.i

.PHONY : src/efsw/FileWatcherImpl.i

# target to preprocess a source file
src/efsw/FileWatcherImpl.cpp.i:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/FileWatcherImpl.cpp.i
.PHONY : src/efsw/FileWatcherImpl.cpp.i

src/efsw/FileWatcherImpl.s: src/efsw/FileWatcherImpl.cpp.s

.PHONY : src/efsw/FileWatcherImpl.s

# target to generate assembly for a file
src/efsw/FileWatcherImpl.cpp.s:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/FileWatcherImpl.cpp.s
.PHONY : src/efsw/FileWatcherImpl.cpp.s

src/efsw/FileWatcherInotify.o: src/efsw/FileWatcherInotify.cpp.o

.PHONY : src/efsw/FileWatcherInotify.o

# target to build an object file
src/efsw/FileWatcherInotify.cpp.o:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/FileWatcherInotify.cpp.o
.PHONY : src/efsw/FileWatcherInotify.cpp.o

src/efsw/FileWatcherInotify.i: src/efsw/FileWatcherInotify.cpp.i

.PHONY : src/efsw/FileWatcherInotify.i

# target to preprocess a source file
src/efsw/FileWatcherInotify.cpp.i:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/FileWatcherInotify.cpp.i
.PHONY : src/efsw/FileWatcherInotify.cpp.i

src/efsw/FileWatcherInotify.s: src/efsw/FileWatcherInotify.cpp.s

.PHONY : src/efsw/FileWatcherInotify.s

# target to generate assembly for a file
src/efsw/FileWatcherInotify.cpp.s:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/FileWatcherInotify.cpp.s
.PHONY : src/efsw/FileWatcherInotify.cpp.s

src/efsw/Log.o: src/efsw/Log.cpp.o

.PHONY : src/efsw/Log.o

# target to build an object file
src/efsw/Log.cpp.o:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/Log.cpp.o
.PHONY : src/efsw/Log.cpp.o

src/efsw/Log.i: src/efsw/Log.cpp.i

.PHONY : src/efsw/Log.i

# target to preprocess a source file
src/efsw/Log.cpp.i:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/Log.cpp.i
.PHONY : src/efsw/Log.cpp.i

src/efsw/Log.s: src/efsw/Log.cpp.s

.PHONY : src/efsw/Log.s

# target to generate assembly for a file
src/efsw/Log.cpp.s:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/Log.cpp.s
.PHONY : src/efsw/Log.cpp.s

src/efsw/Mutex.o: src/efsw/Mutex.cpp.o

.PHONY : src/efsw/Mutex.o

# target to build an object file
src/efsw/Mutex.cpp.o:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/Mutex.cpp.o
.PHONY : src/efsw/Mutex.cpp.o

src/efsw/Mutex.i: src/efsw/Mutex.cpp.i

.PHONY : src/efsw/Mutex.i

# target to preprocess a source file
src/efsw/Mutex.cpp.i:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/Mutex.cpp.i
.PHONY : src/efsw/Mutex.cpp.i

src/efsw/Mutex.s: src/efsw/Mutex.cpp.s

.PHONY : src/efsw/Mutex.s

# target to generate assembly for a file
src/efsw/Mutex.cpp.s:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/Mutex.cpp.s
.PHONY : src/efsw/Mutex.cpp.s

src/efsw/String.o: src/efsw/String.cpp.o

.PHONY : src/efsw/String.o

# target to build an object file
src/efsw/String.cpp.o:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/String.cpp.o
.PHONY : src/efsw/String.cpp.o

src/efsw/String.i: src/efsw/String.cpp.i

.PHONY : src/efsw/String.i

# target to preprocess a source file
src/efsw/String.cpp.i:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/String.cpp.i
.PHONY : src/efsw/String.cpp.i

src/efsw/String.s: src/efsw/String.cpp.s

.PHONY : src/efsw/String.s

# target to generate assembly for a file
src/efsw/String.cpp.s:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/String.cpp.s
.PHONY : src/efsw/String.cpp.s

src/efsw/System.o: src/efsw/System.cpp.o

.PHONY : src/efsw/System.o

# target to build an object file
src/efsw/System.cpp.o:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/System.cpp.o
.PHONY : src/efsw/System.cpp.o

src/efsw/System.i: src/efsw/System.cpp.i

.PHONY : src/efsw/System.i

# target to preprocess a source file
src/efsw/System.cpp.i:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/System.cpp.i
.PHONY : src/efsw/System.cpp.i

src/efsw/System.s: src/efsw/System.cpp.s

.PHONY : src/efsw/System.s

# target to generate assembly for a file
src/efsw/System.cpp.s:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/System.cpp.s
.PHONY : src/efsw/System.cpp.s

src/efsw/Thread.o: src/efsw/Thread.cpp.o

.PHONY : src/efsw/Thread.o

# target to build an object file
src/efsw/Thread.cpp.o:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/Thread.cpp.o
.PHONY : src/efsw/Thread.cpp.o

src/efsw/Thread.i: src/efsw/Thread.cpp.i

.PHONY : src/efsw/Thread.i

# target to preprocess a source file
src/efsw/Thread.cpp.i:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/Thread.cpp.i
.PHONY : src/efsw/Thread.cpp.i

src/efsw/Thread.s: src/efsw/Thread.cpp.s

.PHONY : src/efsw/Thread.s

# target to generate assembly for a file
src/efsw/Thread.cpp.s:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/Thread.cpp.s
.PHONY : src/efsw/Thread.cpp.s

src/efsw/Watcher.o: src/efsw/Watcher.cpp.o

.PHONY : src/efsw/Watcher.o

# target to build an object file
src/efsw/Watcher.cpp.o:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/Watcher.cpp.o
.PHONY : src/efsw/Watcher.cpp.o

src/efsw/Watcher.i: src/efsw/Watcher.cpp.i

.PHONY : src/efsw/Watcher.i

# target to preprocess a source file
src/efsw/Watcher.cpp.i:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/Watcher.cpp.i
.PHONY : src/efsw/Watcher.cpp.i

src/efsw/Watcher.s: src/efsw/Watcher.cpp.s

.PHONY : src/efsw/Watcher.s

# target to generate assembly for a file
src/efsw/Watcher.cpp.s:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/Watcher.cpp.s
.PHONY : src/efsw/Watcher.cpp.s

src/efsw/WatcherGeneric.o: src/efsw/WatcherGeneric.cpp.o

.PHONY : src/efsw/WatcherGeneric.o

# target to build an object file
src/efsw/WatcherGeneric.cpp.o:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/WatcherGeneric.cpp.o
.PHONY : src/efsw/WatcherGeneric.cpp.o

src/efsw/WatcherGeneric.i: src/efsw/WatcherGeneric.cpp.i

.PHONY : src/efsw/WatcherGeneric.i

# target to preprocess a source file
src/efsw/WatcherGeneric.cpp.i:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/WatcherGeneric.cpp.i
.PHONY : src/efsw/WatcherGeneric.cpp.i

src/efsw/WatcherGeneric.s: src/efsw/WatcherGeneric.cpp.s

.PHONY : src/efsw/WatcherGeneric.s

# target to generate assembly for a file
src/efsw/WatcherGeneric.cpp.s:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/WatcherGeneric.cpp.s
.PHONY : src/efsw/WatcherGeneric.cpp.s

src/efsw/WatcherInotify.o: src/efsw/WatcherInotify.cpp.o

.PHONY : src/efsw/WatcherInotify.o

# target to build an object file
src/efsw/WatcherInotify.cpp.o:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/WatcherInotify.cpp.o
.PHONY : src/efsw/WatcherInotify.cpp.o

src/efsw/WatcherInotify.i: src/efsw/WatcherInotify.cpp.i

.PHONY : src/efsw/WatcherInotify.i

# target to preprocess a source file
src/efsw/WatcherInotify.cpp.i:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/WatcherInotify.cpp.i
.PHONY : src/efsw/WatcherInotify.cpp.i

src/efsw/WatcherInotify.s: src/efsw/WatcherInotify.cpp.s

.PHONY : src/efsw/WatcherInotify.s

# target to generate assembly for a file
src/efsw/WatcherInotify.cpp.s:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/WatcherInotify.cpp.s
.PHONY : src/efsw/WatcherInotify.cpp.s

src/efsw/platform/posix/FileSystemImpl.o: src/efsw/platform/posix/FileSystemImpl.cpp.o

.PHONY : src/efsw/platform/posix/FileSystemImpl.o

# target to build an object file
src/efsw/platform/posix/FileSystemImpl.cpp.o:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/platform/posix/FileSystemImpl.cpp.o
.PHONY : src/efsw/platform/posix/FileSystemImpl.cpp.o

src/efsw/platform/posix/FileSystemImpl.i: src/efsw/platform/posix/FileSystemImpl.cpp.i

.PHONY : src/efsw/platform/posix/FileSystemImpl.i

# target to preprocess a source file
src/efsw/platform/posix/FileSystemImpl.cpp.i:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/platform/posix/FileSystemImpl.cpp.i
.PHONY : src/efsw/platform/posix/FileSystemImpl.cpp.i

src/efsw/platform/posix/FileSystemImpl.s: src/efsw/platform/posix/FileSystemImpl.cpp.s

.PHONY : src/efsw/platform/posix/FileSystemImpl.s

# target to generate assembly for a file
src/efsw/platform/posix/FileSystemImpl.cpp.s:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/platform/posix/FileSystemImpl.cpp.s
.PHONY : src/efsw/platform/posix/FileSystemImpl.cpp.s

src/efsw/platform/posix/MutexImpl.o: src/efsw/platform/posix/MutexImpl.cpp.o

.PHONY : src/efsw/platform/posix/MutexImpl.o

# target to build an object file
src/efsw/platform/posix/MutexImpl.cpp.o:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/platform/posix/MutexImpl.cpp.o
.PHONY : src/efsw/platform/posix/MutexImpl.cpp.o

src/efsw/platform/posix/MutexImpl.i: src/efsw/platform/posix/MutexImpl.cpp.i

.PHONY : src/efsw/platform/posix/MutexImpl.i

# target to preprocess a source file
src/efsw/platform/posix/MutexImpl.cpp.i:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/platform/posix/MutexImpl.cpp.i
.PHONY : src/efsw/platform/posix/MutexImpl.cpp.i

src/efsw/platform/posix/MutexImpl.s: src/efsw/platform/posix/MutexImpl.cpp.s

.PHONY : src/efsw/platform/posix/MutexImpl.s

# target to generate assembly for a file
src/efsw/platform/posix/MutexImpl.cpp.s:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/platform/posix/MutexImpl.cpp.s
.PHONY : src/efsw/platform/posix/MutexImpl.cpp.s

src/efsw/platform/posix/SystemImpl.o: src/efsw/platform/posix/SystemImpl.cpp.o

.PHONY : src/efsw/platform/posix/SystemImpl.o

# target to build an object file
src/efsw/platform/posix/SystemImpl.cpp.o:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/platform/posix/SystemImpl.cpp.o
.PHONY : src/efsw/platform/posix/SystemImpl.cpp.o

src/efsw/platform/posix/SystemImpl.i: src/efsw/platform/posix/SystemImpl.cpp.i

.PHONY : src/efsw/platform/posix/SystemImpl.i

# target to preprocess a source file
src/efsw/platform/posix/SystemImpl.cpp.i:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/platform/posix/SystemImpl.cpp.i
.PHONY : src/efsw/platform/posix/SystemImpl.cpp.i

src/efsw/platform/posix/SystemImpl.s: src/efsw/platform/posix/SystemImpl.cpp.s

.PHONY : src/efsw/platform/posix/SystemImpl.s

# target to generate assembly for a file
src/efsw/platform/posix/SystemImpl.cpp.s:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/platform/posix/SystemImpl.cpp.s
.PHONY : src/efsw/platform/posix/SystemImpl.cpp.s

src/efsw/platform/posix/ThreadImpl.o: src/efsw/platform/posix/ThreadImpl.cpp.o

.PHONY : src/efsw/platform/posix/ThreadImpl.o

# target to build an object file
src/efsw/platform/posix/ThreadImpl.cpp.o:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/platform/posix/ThreadImpl.cpp.o
.PHONY : src/efsw/platform/posix/ThreadImpl.cpp.o

src/efsw/platform/posix/ThreadImpl.i: src/efsw/platform/posix/ThreadImpl.cpp.i

.PHONY : src/efsw/platform/posix/ThreadImpl.i

# target to preprocess a source file
src/efsw/platform/posix/ThreadImpl.cpp.i:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/platform/posix/ThreadImpl.cpp.i
.PHONY : src/efsw/platform/posix/ThreadImpl.cpp.i

src/efsw/platform/posix/ThreadImpl.s: src/efsw/platform/posix/ThreadImpl.cpp.s

.PHONY : src/efsw/platform/posix/ThreadImpl.s

# target to generate assembly for a file
src/efsw/platform/posix/ThreadImpl.cpp.s:
	$(MAKE) -f CMakeFiles/efsw.dir/build.make CMakeFiles/efsw.dir/src/efsw/platform/posix/ThreadImpl.cpp.s
.PHONY : src/efsw/platform/posix/ThreadImpl.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... efsw"
	@echo "... edit_cache"
	@echo "... src/efsw/Debug.o"
	@echo "... src/efsw/Debug.i"
	@echo "... src/efsw/Debug.s"
	@echo "... src/efsw/DirWatcherGeneric.o"
	@echo "... src/efsw/DirWatcherGeneric.i"
	@echo "... src/efsw/DirWatcherGeneric.s"
	@echo "... src/efsw/DirectorySnapshot.o"
	@echo "... src/efsw/DirectorySnapshot.i"
	@echo "... src/efsw/DirectorySnapshot.s"
	@echo "... src/efsw/DirectorySnapshotDiff.o"
	@echo "... src/efsw/DirectorySnapshotDiff.i"
	@echo "... src/efsw/DirectorySnapshotDiff.s"
	@echo "... src/efsw/FileInfo.o"
	@echo "... src/efsw/FileInfo.i"
	@echo "... src/efsw/FileInfo.s"
	@echo "... src/efsw/FileSystem.o"
	@echo "... src/efsw/FileSystem.i"
	@echo "... src/efsw/FileSystem.s"
	@echo "... src/efsw/FileWatcher.o"
	@echo "... src/efsw/FileWatcher.i"
	@echo "... src/efsw/FileWatcher.s"
	@echo "... src/efsw/FileWatcherCWrapper.o"
	@echo "... src/efsw/FileWatcherCWrapper.i"
	@echo "... src/efsw/FileWatcherCWrapper.s"
	@echo "... src/efsw/FileWatcherGeneric.o"
	@echo "... src/efsw/FileWatcherGeneric.i"
	@echo "... src/efsw/FileWatcherGeneric.s"
	@echo "... src/efsw/FileWatcherImpl.o"
	@echo "... src/efsw/FileWatcherImpl.i"
	@echo "... src/efsw/FileWatcherImpl.s"
	@echo "... src/efsw/FileWatcherInotify.o"
	@echo "... src/efsw/FileWatcherInotify.i"
	@echo "... src/efsw/FileWatcherInotify.s"
	@echo "... src/efsw/Log.o"
	@echo "... src/efsw/Log.i"
	@echo "... src/efsw/Log.s"
	@echo "... src/efsw/Mutex.o"
	@echo "... src/efsw/Mutex.i"
	@echo "... src/efsw/Mutex.s"
	@echo "... src/efsw/String.o"
	@echo "... src/efsw/String.i"
	@echo "... src/efsw/String.s"
	@echo "... src/efsw/System.o"
	@echo "... src/efsw/System.i"
	@echo "... src/efsw/System.s"
	@echo "... src/efsw/Thread.o"
	@echo "... src/efsw/Thread.i"
	@echo "... src/efsw/Thread.s"
	@echo "... src/efsw/Watcher.o"
	@echo "... src/efsw/Watcher.i"
	@echo "... src/efsw/Watcher.s"
	@echo "... src/efsw/WatcherGeneric.o"
	@echo "... src/efsw/WatcherGeneric.i"
	@echo "... src/efsw/WatcherGeneric.s"
	@echo "... src/efsw/WatcherInotify.o"
	@echo "... src/efsw/WatcherInotify.i"
	@echo "... src/efsw/WatcherInotify.s"
	@echo "... src/efsw/platform/posix/FileSystemImpl.o"
	@echo "... src/efsw/platform/posix/FileSystemImpl.i"
	@echo "... src/efsw/platform/posix/FileSystemImpl.s"
	@echo "... src/efsw/platform/posix/MutexImpl.o"
	@echo "... src/efsw/platform/posix/MutexImpl.i"
	@echo "... src/efsw/platform/posix/MutexImpl.s"
	@echo "... src/efsw/platform/posix/SystemImpl.o"
	@echo "... src/efsw/platform/posix/SystemImpl.i"
	@echo "... src/efsw/platform/posix/SystemImpl.s"
	@echo "... src/efsw/platform/posix/ThreadImpl.o"
	@echo "... src/efsw/platform/posix/ThreadImpl.i"
	@echo "... src/efsw/platform/posix/ThreadImpl.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

